[build]
  base = "https://github.com/abhaypatel099/valuesthroughgitacontest"              
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
